### ISSUE TITLE
How to configure my own Jenkins?

### ISSUE THREAD

**Issue by mahham1947** [Infosys/openIDP#10]
Sorry to bother you.

This seems too complicated to atleast install and try. The underlying arch uses Jenkins and other open surce tools. This seems to be an wrapper written over existing tools. 

Just outa couriosity, wanted to check how this so called "product" from Infosys is better than existing CI-CD tools.

Clarify me few points:

1. How to configure my Jenkins?
2. How to use SCM without username or password? Shouldn't there be a way to connect with Access Token provided by Git?
3. How to hook into a repo and automatically trigger a build when a change is committed?
4. Why there were many dummy constants like "asadad", "adadada", "dahhfjfhs" in few JSON?
5. Is there any "easy" way to atleast test this "product"?

What or How does openIDP different than existing tools?

If openIDP is better, then why TravisCI is used for showing build status? Why cant Infosys host its openIDP on some public server and build via same tool?

Too many open issues or questions unanswered!!!

**Comment by idp-oss** [comment]
Most of you are queries are already answered in the WIKI Page (https://github.com/Infosys/openIDP/wiki)
This platform comes up with one touch installation, not sure why it should be complex !  Once you have installed the platform and started to use it, most of your queries would be clarified. 

-The setup installs Jenkins with all the needed Jenkins Plugins, Custom Utilities and optimizations which do not come in stock Jenkins. Also some of the enhancements are tied up with how platform handshakes with Jenkins in workflow,  hence we don’t recommend to use it with your Jenkins Instance
-You could key-in your access token in the SCM Password field and user name and it should work. This is more to do with how git handles credentials 
- For Git hooks, you can invoke the Pipeline APIs with an non-expiring JWT token . Refer https://github.com/Infosys/openIDP/wiki/Job-Services
- Specify the JSON files where you are seeing this
- Again , if you run the Script, whole platform gets installed and you are ready to use .The Build script seamlessly works across multiple platforms and is able to setup platform with only pre-requisite being Docker.
If you are facing any issue then raise a separate issue using format given at following link : https://github.com/Infosys/openIDP/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

We will be closing this issue for now. Please feel free to log new bug/feature request.

**Comment by user-karthik-kumar** [comment]
I agree with @mahham1947 query! Too complex!
