### ISSUE TITLE
SKIP_TESTS parameter should be false by default

### ISSUE THREAD

**Issue by manishbansal8843** [Infosys/openIDP#18]
**Describe the bug**
In build.sh, SKIP_TESTS parameter should be false by default. Also, it's description should be corrected in wiki page [here](https://github.com/Infosys/openIDP/wiki/Installation#additional-notes-on-setup-script-buildsh-variables). 
**To Reproduce**
NA

**Expected behavior**
SKIP_TESTS parameter should be false by default in build.sh.
Also, the wiki page should read like this.

> SKIP_TESTS
> Default Value: false
> Allowed Values: true | false
> Implications: If set true, will skip the test during build. If set false, then test cases will execute with build section. 

**Screenshots**
NA
**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by Chids-gs** [comment]
@manishbansal8843 thanks for your suggestion. But ideally while installing, we don't want to run Unit testing. These tests would be run as part of the CI Pipelines

**Comment by manishbansal8843** [comment]
@Chids-gs I still strongly feel that it should be enabled during build time as well. It will help in validating the sources at build time so that a user does not face surprises at run time. See issue #22 . There are unit tests error as of now.
