### ISSUE TITLE
Getting permission errors while executing build.sh

### ISSUE THREAD

**Issue by manishbansal8843** [Infosys/openIDP#21]
**Describe the bug**
Getting permission denied error while executing build.sh. This is happening while docker container is getting executed while "Compiling Cloud config". Error thrown is as below:

> Can not write to /root/.m2/copy_reference_file.log. Wrong Permissions?

**To Reproduce**
1. Spin up a t2.micro instance on AWS with RHEL image.
2. su root
3. Install git and docker.
4. Initialize docker swarm.
5. Execute sh build.sh

**Expected behavior**
build.sh should get executed without any issues.

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS: RHEL
 - Browser: NA
 - Version 7

**Additional context**
NA

**Comment by jaskirat8** [comment]
This was done to allow re-use of maven artifacts across builds. You can disable it by commenting the "LOCAL_M2_CACHE" line in build.sh or change the folder before colon to something like 
LOCAL_M2_CACHE="-v /home/<your-username>/.m2/:/root/.m2/"

**Comment by manishbansal8843** [comment]
Its not just maven local repo. All the host volume mounts are giving error. Check my second commit for the fix. I think, the issue is due to SELinux policy of docker containers. Please refer [this ](http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)for more details.

**Comment by jaskirat8** [comment]
@manishbansal8843 To modify your Selinux label on single image is one thing and for bunch of paths is another. Although i agree to your suggestion but thing is this will have implications for non-advanced users , also highlighted by Docker Team [here](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label).

Hence, genuine way will be to manually make label or much better is have IDP build trigger in user directories where selinux policy is relaxed.
