### ISSUE TITLE
Log aggregation using ELK stack

### ISSUE THREAD

**Issue by manishbansal8843** [Infosys/openIDP#24]
**Is your feature request related to a problem? Please describe.**
As of now, I need to poke each container using below command to get the logs out. 
`docker logs -f <Container_id>`
**Describe the solution you'd like**
It would have been awesome if some log aggregation was used like ELK stack.
**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by krishnakanthbn** [comment]
@manishbansal8843 Thanks for your interest and suggestion. Hope Jaskirat's response was helpful. Closing this issue for now.
