### ISSUE TITLE
Review State of Devops 2019 report & Prepare Roadmap

### ISSUE THREAD

**Issue by jayanmai** [Infosys/openIDP#38]
State of Devops 2019 Report: 
https://services.google.com/fh/files/misc/state-of-devops-2019.pdf

**Is your feature request related to a problem? Please describe.**
This feature request is towards making openidp more relevant and usable.

**Describe the solution you'd like**
The link to the state of devops report for 2019 is attached.  It would make sense to go through it and brainstorm on how the onward trajectory of openidp should look like. 

**Describe alternatives you've considered**
Jenkins, Jenkins X, Circle CI, prow etc. 

**Additional context**

**Comment by krishnakanthbn** [comment]
Thanks for sharing this. Yes. We have got this. We are working on this.
