### ISSUE TITLE
Image 'paasmule / java-maven-git-alpine: 3.3-jdk-8-alpine' does not exist in the docker hub

### ISSUE THREAD

**Issue by namthz** [Infosys/openIDP#78]
**Describe the bug**
I clone the project and I run `bash build.sh` then:

`[root@localhost openIDP]# bash build.sh 
Evaluating Hardware
Clearing Memory for Setup ...
CPU Load: 0.40
Memory Usage: 1/31GB (3.23%)
Disk Usage(Datafiles Directory): 601/1113760GB (1%)
Disk Usage (Docker Data Directory): 7433/51175GB (15%)
Your Setup Failed to meet recommended Memory Requirements (32GB). Continue ?
1) Yes
2) No
#? 1
Recommended Disk Space for Docker Images not available (15360MB). Continue ?
1) Yes
2) No
#? 1 
Checking Pre-requisites
Checking for Docker and Swarm Mode
Docker Check: Passed
Checking if interactive session
Running in Interactive Session
Checking for selected ports open status
Starting port check .......
 Checking HTTP Server Port (80): Passed
 Checking CI Engine Client Port (50000): Passed
Port Check: Passed
Compiling openidp parent pom .......
Unable to find image 'paasmule/java-maven-git-alpine:3.3-jdk-8-alpine' locally
docker: Error response from daemon: pull access denied for paasmule/java-maven-git-alpine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

Image 'paasmule / java-maven-git-alpine: 3.3-jdk-8-alpine' does not exist in the docker hub

**Expected behavior**
image 'paasmule / java-maven-git-alpine: 3.3-jdk-8-alpine' exists in docker hub.

**Screenshots**
![Screen Shot 2020-09-25 at 15 15 03](https://user-images.githubusercontent.com/58029441/94243659-e5b4a600-ff41-11ea-9607-86441c2746b8.png)

**Desktop (please complete the following information):**
 - OS: Centos7
 - Docker version 19.03.13, build 4484c46d9d

**Comment by jvinaya** [comment]
Hi @namthz ,

Looks like image 'paasmule / java-maven-git-alpine: 3.3-jdk-8-alpine' no more exists in docker hub. Could you replace the image in build.sh with some other maven image(for ex - maven:3.6-jdk-8-openj9) and try?

**Comment by namthz** [comment]
Hi @jvinaya, thank you,
I have built an image with 3 components jdk8, maven and git.
This image replaces the missing image and starts the project successfully.
