### ISSUE TITLE
Where is executable JAR/WAR?

### ISSUE THREAD

**Issue by mahham1947** [Infosys/openIDP#9]
Where is executable JAR/WAR?

**Comment by sushanthmangalore** [comment]
There isn't going to be a single executable JAR/WAR for the platform. The installation steps have been detailed in the Wiki. Because this is a containerized platform, you will require a Docker enabled host machine to install the platform on.

**Comment by idp-oss** [comment]
> Where is executable JAR/WAR?

Hi,

As @sushanthmangalore pointed out, the executable JARs of all the microservices are packaged in separate Docker images during the execution of build.sh script and the containers are started and managed through Docker Swarm. 

Thanks @sushanthmangalore .
